- action: query
  namespace: brent-billing-project
  workspace: covid_RNA_qtl_v2
  entity: sample
- action: subset
  name: select a few samples by value and regular-expression
  values:
      - VAR15966-20
      - BQC10336.VAR09082-20
  regexps:
      - BQC100.*-20
- action: sample
  name: take 10 rows from the top
  head: 10
- action: select
  name: choose some columns by value and regular-expression
  values:
    - blacklisted_Q
  regexps:
    - .*index
- action: localize
## default, optional when false, local path is generated, but files are not downloaded
  actually_localize: True
  name: localize things that look like gs:// files
  hash: crc32
  map:
    deduped_bam_index: deduped_bam
    snps_het_vcf_index: snps_het_vcf
    bam_index: bam_file
    snps_vcf_index: snps_vcf
  directory: data_mirror
- action: write
## default Fail; value can be Fail, Always or Ask
  overwrite: False
  name: write data to a local file
  output: mirror.json


