# change this to include the packages you need 
channels:
  - conda-forge
dependencies:
  - python=>3.8
  - conda-forge::gsutil==5.6
  - conda-forge::google-cloud-sdk
  - pip
  - pip:
      - tqdm
      - google-cloud-storage
      - firecloud
      - PyYAML
