# change this to include the packages you need 
channels:
  - conda-forge
dependencies:
  - python=>3.8
  - conda-forge::google-cloud-sdk
  - pip==19.3.1
  - pip:
      - tqdm
      - google-cloud-storage
      - firecloud
      - PyYAML
      - defopt
