# change this to include the packages you need 
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - conda-forge::gsutil==5.6
  - pip:
      - tqdm
      - google-cloud-storage
      - firecloud
      - yaml
